import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'app-services',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section id="coffee" class="mt-24 sm:mt-32 lg:mt-44 px-4 sm:px-6 reveal">
      <div class="text-center max-w-3xl mx-auto mb-16 lg:mb-24"><span class="text-primary-400 font-bold uppercase text-sm tracking-[0.2em] mb-4 block">Specialty Coffee</span><h2 class="section-title">Coffee, Made With Intention.</h2><p class="text-cream/60 text-base sm:text-lg leading-relaxed">From classic espresso drinks to carefully prepared manual brews, MERZY focuses on the details that make a great cup of coffee.</p></div>
      <div class="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-6 lg:gap-8">
        <article class="group bg-dark-900 rounded-[2rem] border border-primary-400/10 p-10 text-center hover:border-primary-400/40 hover:-translate-y-2 transition-all duration-500"><div class="w-20 h-20 rounded-full bg-dark-800/80 border border-primary-400/20 flex items-center justify-center mx-auto mb-8"><svg class="w-9 h-9 text-primary-400" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M12 8v-4m4 4v-4m-8 4v-4M5.25 8h13.5v9a3.75 3.75 0 01-3.75 3.75h-6A3.75 3.75 0 015.25 17V8zM18.75 11.25h1.125A1.875 1.875 0 0121.75 13.125v.75a1.875 1.875 0 01-1.875 1.875h-1.125V11.25z"/></svg></div><h3 class="text-xl font-macondo text-cream mb-4 tracking-tight">Espresso</h3><p class="text-cream/60 text-sm leading-relaxed">Rich, balanced and carefully extracted for a clean, satisfying cup.</p></article>
        <article class="group bg-dark-900 rounded-[2rem] border border-primary-400/10 p-10 text-center hover:border-primary-400/40 hover:-translate-y-2 transition-all duration-500"><div class="w-20 h-20 rounded-full bg-dark-800/80 border border-primary-400/20 flex items-center justify-center mx-auto mb-8"><svg class="w-9 h-9 text-primary-400" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M6 3v18M18 3v18M3 8h18M3 16h18"/></svg></div><h3 class="text-xl font-macondo text-cream mb-4 tracking-tight">V60</h3><p class="text-cream/60 text-sm leading-relaxed">A manual brew designed to reveal the character, aroma and delicate flavors of specialty coffee.</p></article>
        <article class="group bg-dark-900 rounded-[2rem] border border-primary-400/10 p-10 text-center hover:border-primary-400/40 hover:-translate-y-2 transition-all duration-500"><div class="w-20 h-20 rounded-full bg-dark-800/80 border border-primary-400/20 flex items-center justify-center mx-auto mb-8"><svg class="w-9 h-9 text-primary-400" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M12 3v18m-6-9h12"/></svg></div><h3 class="text-xl font-macondo text-cream mb-4 tracking-tight">Signature Drinks</h3><p class="text-cream/60 text-sm leading-relaxed">Hot and cold creations for modern coffee lovers, with seasonal flavors and new favorites appearing throughout the year.</p></article>
      </div>
      <div id="bakery" class="mt-16 sm:mt-24 relative h-[420px] rounded-[2.5rem] overflow-hidden border border-primary-400/10"><img src="https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=1400&auto=format&fit=crop" alt="Fresh pastries and bakery details" width="1400" height="700" loading="lazy" class="absolute inset-0 w-full h-full object-cover animate-imageSlowZoom"><div class="absolute inset-0 bg-gradient-to-r from-dark-900 via-dark-900/70 to-dark-900/20"></div><div class="relative h-full max-w-xl flex flex-col justify-center p-8 sm:p-14"><span class="text-primary-400 font-bold uppercase text-xs tracking-[0.3em] mb-4">The Bakery</span><h2 class="text-4xl sm:text-5xl font-macondo text-cream mb-5">Baked Fresh. Made To Go With Coffee.</h2><p class="text-cream/70 leading-relaxed">Coffee deserves something good beside it. Our bakery brings freshly prepared pastries and desserts to the MERZY experience, made for slow mornings, afternoon breaks and everything in between.</p></div></div>
    </section>
  `,
})
export class ServicesComponent {}
