import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'app-process',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section id="experience" class="mt-24 sm:mt-32 lg:mt-44 px-4 sm:px-6 reveal">
      <div class="text-center max-w-3xl mx-auto mb-16 lg:mb-20"><span class="text-primary-400 font-bold uppercase text-sm tracking-[0.2em] mb-4 block">The MERZY Experience</span><h2 class="section-title">Your Coffee Break, Your Way</h2><p class="text-cream/60 text-base sm:text-lg leading-relaxed">Come for a quick stop, settle in with something slow, or make MERZY part of your day in Alexandria.</p></div>
      <div class="max-w-6xl mx-auto grid grid-cols-1 sm:grid-cols-2 gap-6">
        <article class="relative min-h-[280px] rounded-[2rem] overflow-hidden border border-primary-400/10 group"><img src="https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?q=80&w=900&auto=format&fit=crop" alt="Morning coffee in a modern café" width="900" height="620" loading="lazy" class="absolute inset-0 w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"><div class="absolute inset-0 bg-gradient-to-t from-dark-900 via-dark-900/50 to-transparent"></div><div class="absolute left-8 right-8 bottom-8"><span class="text-primary-400 text-xs font-bold uppercase tracking-[0.25em]">Morning</span><h3 class="text-3xl font-macondo text-cream mt-2">Start Well</h3><p class="text-cream/70 text-sm mt-3 max-w-sm">Start the day with specialty coffee and something freshly baked.</p></div></article>
        <article class="relative min-h-[280px] rounded-[2rem] overflow-hidden border border-primary-400/10 group"><img src="https://images.unsplash.com/photo-1498804103079-a6351b050096?q=80&w=900&auto=format&fit=crop" alt="Coffee break with pastry" width="900" height="620" loading="lazy" class="absolute inset-0 w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"><div class="absolute inset-0 bg-gradient-to-t from-dark-900 via-dark-900/50 to-transparent"></div><div class="absolute left-8 right-8 bottom-8"><span class="text-primary-400 text-xs font-bold uppercase tracking-[0.25em]">Afternoon</span><h3 class="text-3xl font-macondo text-cream mt-2">Take A Break</h3><p class="text-cream/70 text-sm mt-3 max-w-sm">Take a break with a V60, signature drink or pastry.</p></div></article>
        <article class="relative min-h-[280px] rounded-[2rem] overflow-hidden border border-primary-400/10 group"><img src="https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=900&auto=format&fit=crop" alt="Coffee prepared for a library visit" width="900" height="620" loading="lazy" class="absolute inset-0 w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"><div class="absolute inset-0 bg-gradient-to-t from-dark-900 via-dark-900/50 to-transparent"></div><div class="absolute left-8 right-8 bottom-8"><span class="text-primary-400 text-xs font-bold uppercase tracking-[0.25em]">After The Library</span><h3 class="text-3xl font-macondo text-cream mt-2">Meet In The Middle</h3><p class="text-cream/70 text-sm mt-3 max-w-sm">The perfect stop before or after exploring the Bibliotheca Alexandrina.</p></div></article>
        <article class="relative min-h-[280px] rounded-[2rem] overflow-hidden border border-primary-400/10 group"><img src="https://images.unsplash.com/photo-1469474968028-56623f02e42e?q=80&w=900&auto=format&fit=crop" alt="Mediterranean blue horizon" width="900" height="620" loading="lazy" class="absolute inset-0 w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"><div class="absolute inset-0 bg-gradient-to-t from-dark-900 via-dark-900/50 to-transparent"></div><div class="absolute left-8 right-8 bottom-8"><span class="text-primary-400 text-xs font-bold uppercase tracking-[0.25em]">By The Sea</span><h3 class="text-3xl font-macondo text-cream mt-2">Alexandria, Around You</h3><p class="text-cream/70 text-sm mt-3 max-w-sm">Good coffee tastes better with Alexandria's Mediterranean atmosphere around you.</p></div></article>
      </div>
    </section>
  `,
})
export class ProcessComponent {}
